# Generated by Django 4.0.4 on 2022-05-31 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import occurrences.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesOccurrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=320, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número')),
                ('latitude', models.IntegerField(verbose_name='Latitude')),
                ('longitude', models.IntegerField(verbose_name='Longitude')),
                ('status', models.CharField(choices=[('NOT_COMPLETED', 'Não concluida'), ('COMPLETED', 'Completa'), ('DELETED', 'Deletada')], default='NOT_COMPLETED', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=occurrences.models.upload_image_occurrences)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='occurrences.categoriesoccurrences')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=320, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('occurrences', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='occurrences.occurrences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'Curtir')], default='LIKE', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('occurrences', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='occurrences.occurrences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
