# Generated by Django 4.0.4 on 2022-05-31 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccurrencesActions',
            new_name='Actions',
        ),
        migrations.RenameModel(
            old_name='CategoriesOccurrences',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='OccurrencesComments',
            new_name='Comments',
        ),
    ]
