# Generated by Django 4.0.4 on 2022-06-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_alter_categories_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrences',
            name='latitude',
            field=models.CharField(max_length=120, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='occurrences',
            name='longitude',
            field=models.CharField(max_length=120, verbose_name='Longitude'),
        ),
    ]
