# Generated by Django 4.0.4 on 2022-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_alter_occurrences_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrences',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Compemento'),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='point',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ponto'),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='UF'),
        ),
    ]
