# Generated by Django 4.0.4 on 2022-06-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_occurrences_city_occurrences_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='color',
            field=models.CharField(blank=True, default='', max_length=180, null=True),
        ),
    ]
